# Generated by Django 2.2.11 on 2020-03-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_auto_20200328_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='bookshop.Book'),
            preserve_default=False,
        ),
    ]
