# Generated by Django 2.2.11 on 2020-04-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_auto_20200402_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default=None, height_field=100, upload_to='gallery/', width_field=100),
            preserve_default=False,
        ),
    ]
