# Generated by Django 2.2.11 on 2020-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_book_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='picture',
        ),
    ]
